filebeat.inputs:
- type: filestream
  enabled: true
  id: my-sample-log-collector
  take_over: true
  paths:
    - ./test/*.log

output.kafka:
  hosts: ["localhost:9092"]
  topic: "json_topic"
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000